[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "InstanSeg"
version = "0.1.0"
authors = [
  { name="Thibaut Goldsborough", email="thibaut.golds@ed.ac.uk" },
]
description = "A package for instance segmentation using deep learning."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/instanseg/instanseg"
Issues = "https://github.com/instanseg/instanseg/issues"
